# Generated by Django 3.1.7 on 2021-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('cpf', models.IntegerField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('celular', models.IntegerField(max_length=11)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.IntegerField(max_length=5)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
            ],
        ),
    ]
