# Generated by Django 3.1.7 on 2021-04-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0003_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
