# Generated by Django 3.1.7 on 2021-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
