# Generated by Django 3.1.7 on 2021-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0006_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(max_length=8)),
                ('cliente', models.CharField(max_length=150)),
                ('produtos', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
