# Generated by Django 3.1.7 on 2021-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0007_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
