# Generated by Django 3.1.7 on 2021-05-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0008_auto_20210504_1521'),
    ]


