# Generated by Django 3.1.7 on 2021-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0010_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
