# Generated by Django 3.1.7 on 2021-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0013_auto_20210507_1620'),
    ]

