# Generated by Django 3.1.7 on 2021-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0014_auto_20210511_1435'),
    ]

 