# Generated by Django 3.1.7 on 2021-05-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0016_auto_20210512_1524'),
    ]

