# Generated by Django 3.1.7 on 2021-05-19 19:03

import adsports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0018_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(),
        ),
    ]
