# Generated by Django 3.1.7 on 2021-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0019_auto_20210519_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
