# Generated by Django 3.1.7 on 2021-05-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0020_auto_20210519_1616'),
    ]
