# Generated by Django 3.1.7 on 2021-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0021_delete_administradores'),
    ]

