# Generated by Django 3.1.7 on 2021-06-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0023_remove_produtos_imagem'),
    ]


