# Generated by Django 3.1.7 on 2021-06-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0030_auto_20210607_1630'),
    ]
