# Generated by Django 3.1.7 on 2021-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0031_auto_20210607_1630'),
    ]
