# Generated by Django 3.1.7 on 2021-06-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0033_auto_20210607_1707'),
    ]

