# Generated by Django 3.1.7 on 2021-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsports', '0034_auto_20210610_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=150)),
                ('nome_produto', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Administradores',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
